name: AutoBroadcast
main: net.nikdev.autobroadcast.AutoBroadcast
version: 2.0-SNAPSHOT
author: NickTheDev
website: http://nikdev.net/

commands:
  broadcast:
    aliases: [broadc, bcast, bc]
    description: Broadcasts the specified messages.
  broadcasttoggle:
    aliases: [broadcastt, togglebroadcast, bct]
    description: Toggles whether or not timed broadcasts are dispatched.

permissions:
  autobroadcast.broadcast:
    description: Allows you to use /broadcast.
    default: op
  autobroadcast.toggle:
    description: Allows you do use /broadcasttoggle
    default: op